[package]
name = "termie"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.0"
nix = { version = "0.30.1", default-features = false, features = ["term", "process", "fs"] }
tokio = { version = "1.48.0", features = ["full"] }
